In [10]:
import pandas as pd
import os

In [17]:
ruta = os.getcwd()
path=(f"{ruta}/datos.json")


df = pd.read_json(path)
df.head(10)

,RUT_ENCARGADO,NOMBRE_ENCARGADO,APELLIDO_ENCARGADO,ID_CONTINENTE,CONTINENTE,ID_PAIS,NOMBRE_PAIS,ID_CIUDAD,NOMBRE_CIUDAD,ID_ZOOLOGICO,...,N_IDENTIFICACION,NOMBRE_ANIMAL,NOMBRE_CIENTIFICO,ESTADO_CONCERVACION,SEXO_ANIMAL,ANIO_NACIMIENTO,ID_ESPECIE,NOMBRE_ESPECIE,ID_FAMILIA,NOMBRE_FAMILIA
0,18000120-3,CARLOS,MALDONADO,1,AMERICA,1,CHILE,101,ANGOL,1001,...,255,ELEFANTE,ELEFANTUS,A,F,2015-01-01,10001,ELEELE,3003,FUFU
1,18000121-4,MARTINA,RODRIGUEZ,2,EUROPA,2,FRANCIA,102,PARIS,1002,...,256,TIGRE,PANTHERA TIGRIS,B,M,2016-03-15,10002,BIGCAT,3004,FELIDAE
2,18000122-5,ISABEL,LOPEZ,3,ASIA,3,JAPON,103,TOKIO,1003,...,257,PANDA,AILUROPODA MELANOLEUCA,C,F,2018-02-10,10003,BEAR,3005,URSIDAE
3,18000123-6,ANTONIO,SANCHEZ,4,AFRICA,4,EGIPTO,104,EL CAIRO,1004,...,258,LEON,PANTHERA LEO,D,M,2019-05-12,10004,BIGCAT,3004,FELIDAE
4,18000124-7,MARIA,PEREZ,5,OCEANIA,5,AUSTRALIA,105,SYDNEY,1005,...,259,KOALA,PHASCOLARCTOS CINEREUS,E,F,2017-08-09,10005,MARSUPIAL,3006,PHASCOLARCTIDAE
5,18000125-8,FERNANDO,GUTIERREZ,6,ANTARCTICA,6,NINGUNO,106,NINGUNA,1006,...,260,PENGUINO,APTENODYTES FORSTERI,F,M,2020-11-11,10006,BIRD,3007,SPHENISCIDAE
6,18000126-9,SOFIA,TORRES,2,EUROPA,7,ITALIA,107,ROMA,1007,...,261,LOBEZNO,CANIS LUPUS,B,M,2021-03-21,10007,CANID,3008,CANIDAE
7,18000127-0,ALFREDO,VARGAS,3,ASIA,8,INDIA,108,NUEVA DELHI,1008,...,262,TIGRE DE BENGALA,PANTHERA TIGRIS TIGRIS,C,F,2020-09-09,10008,BIGCAT,3004,FELIDAE